// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 */

package main

import (
	"go.uber.org/fx"
	"github.com/gin-gonic/gin"
	"github.com/sherlockhua/koala/logs"
	"github.com/sherlockhua/koala/config"
	"github.com/sherlockhua/koala/env"
	
	openapi "notify/go"
)




func main() {
	if env.IsOnline() {
		gin.SetMode(gin.ReleaseMode)
	}
	
	filename := "./configs/config.yml"
	app := fx.New(
		fx.Provide(
			func() config.ConfigFile {
					return config.ConfigFile(filename) // 这里提供你需要的字符串依赖
			},
		),
		openapi.Module,
		logs.Module,
		config.Module,
		fx.Invoke(func(server *openapi.Server,  conf *config.Config,logger logs.Logger) error {
			go server.Run(conf.Server.ListenAddr)
			return nil
		}),
	)
	app.Run()
}
